name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ] # Ajuste para 'master' se sua branch principal não for 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # Ou '9.0.x' conforme o SDK do seu projeto

      - name: Publish Blazor App
        run: dotnet publish -c Release -o release

      - name: Bypass Jekyll & SPA Fallback
        run: |
          touch release/wwwroot/.nojekyll
          cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          FOLDER: release/wwwroot
          BRANCH: gh-pages